#!/bin/bash
#
# Solana Edition 2024 Fixer - Shell Script
#
# Quick fix for Rust edition 2024 compatibility issues in Solana/Anchor projects.
# This is a standalone script that can be run without Node.js.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/volta-team/solana-edition-fixer/main/scripts/fix-edition2024.sh | bash
#   # or
#   ./fix-edition2024.sh [project-path]
#
# Created by: Volta Team
# License: MIT
#

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BLUE='\033[0;34m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

PROJECT_PATH="${1:-.}"

# Print banner
echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                                                                    ║${NC}"
echo -e "${CYAN}║   ${BOLD}Solana Edition 2024 Fixer${NC}${CYAN}                                        ║${NC}"
echo -e "${CYAN}║   Fix Rust edition 2024 compatibility for Solana/Anchor           ║${NC}"
echo -e "${CYAN}║                                                                    ║${NC}"
echo -e "${CYAN}║   Created by Volta Team                                            ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Comprehensive list of crates to downgrade
# Format: "crate_name:max_compatible_version"
# Ordered by priority (critical first)
CRATES_TO_FIX=(
    # CRITICAL - Most common causes of build failures
    "blake3:1.5.0"
    "constant_time_eq:0.3.1"

    # HIGH - Crypto crates used by Solana
    "base64ct:1.6.0"
    "subtle:2.5.0"
    "zeroize:1.7.0"
    "crypto-common:0.1.6"
    "digest:0.10.7"
    "sha2:0.10.8"
    "sha3:0.10.8"
    "signature:2.2.0"
    "yoke:0.7.4"
    "wit-bindgen:0.24.0"
    "curve25519-dalek:4.1.3"
    "ed25519-dalek:2.1.1"

    # MEDIUM - Less common but still problematic
    "password-hash:0.5.0"
    "cipher:0.4.4"
    "aead:0.5.2"
    "inout:0.1.3"
    "universal-hash:0.5.1"
    "elliptic-curve:0.13.8"
    "sec1:0.7.3"
    "spki:0.7.3"
    "pkcs8:0.10.2"
    "der:0.7.9"
    "wit-component:0.24.0"
    "wit-parser:0.24.0"
    "wasm-encoder:0.41.0"
    "wasmparser:0.121.0"
    "zerofrom:0.1.4"
    "zerovec:0.10.4"
    "borsh:1.5.0"
    "borsh-derive:1.5.0"
    "hmac:0.12.1"
    "pbkdf2:0.12.2"
    "aes:0.8.4"
    "aes-gcm:0.10.3"
    "chacha20:0.9.1"

    # LOW - Rarely encountered
    "pem-rfc7468:0.7.0"
    "chacha20poly1305:0.10.1"
    "x25519-dalek:2.0.1"
)

# Check if project path exists
if [ ! -d "$PROJECT_PATH" ]; then
    echo -e "${RED}Error: Project path '$PROJECT_PATH' does not exist${NC}"
    exit 1
fi

cd "$PROJECT_PATH"

# Check for Cargo.toml
if [ ! -f "Cargo.toml" ]; then
    echo -e "${RED}Error: No Cargo.toml found in $(pwd)${NC}"
    exit 1
fi

echo -e "${BLUE}Project: $(pwd)${NC}"
echo ""

# Step 1: Create .cargo/config.toml if it doesn't exist
echo -e "${YELLOW}Step 1: Setting up Cargo configuration${NC}"
mkdir -p .cargo

if [ ! -f ".cargo/config.toml" ]; then
    cat > .cargo/config.toml << 'CARGO_CONFIG'
# Cargo configuration for Solana/Anchor compatibility
# Generated by solana-edition-fixer
# https://github.com/volta-team/solana-edition-fixer

[resolver]
# MSRV-aware resolver - prefer versions compatible with rust-version
# Requires Cargo 1.84+ to have effect
incompatible-rust-versions = "fallback"

[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"
CARGO_CONFIG
    echo -e "${GREEN}  ✓ Created .cargo/config.toml${NC}"
else
    echo -e "${DIM}  - .cargo/config.toml already exists${NC}"
fi
echo ""

# Step 2: Check/generate Cargo.lock
echo -e "${YELLOW}Step 2: Checking Cargo.lock${NC}"
if [ ! -f "Cargo.lock" ]; then
    echo "  Generating Cargo.lock..."
    if ! cargo generate-lockfile 2>/dev/null; then
        if ! cargo check 2>/dev/null; then
            echo -e "${RED}  ✗ Could not generate Cargo.lock${NC}"
            echo -e "${DIM}  Try running 'cargo check' manually to see errors${NC}"
            exit 1
        fi
    fi
fi
echo -e "${GREEN}  ✓ Cargo.lock exists${NC}"
echo ""

# Step 3: Downgrade problematic crates
echo -e "${YELLOW}Step 3: Fixing problematic dependencies${NC}"
echo ""

UPDATED=0
SKIPPED=0
FAILED=0

for entry in "${CRATES_TO_FIX[@]}"; do
    crate_name="${entry%%:*}"
    max_version="${entry##*:}"

    # Check if crate is in Cargo.lock
    if grep -q "name = \"$crate_name\"" Cargo.lock 2>/dev/null; then
        # Get current version
        current_version=$(grep -A1 "name = \"$crate_name\"" Cargo.lock | grep "version" | head -1 | sed 's/.*"\([^"]*\)".*/\1/')

        if [ -n "$current_version" ]; then
            # Compare versions using sort -V
            higher_version=$(echo -e "$current_version\n$max_version" | sort -V | tail -1)

            if [ "$higher_version" = "$current_version" ] && [ "$current_version" != "$max_version" ]; then
                echo -e "  ${YELLOW}⚠ $crate_name${NC}"
                echo -e "    ${RED}Current: $current_version${NC}"
                echo -e "    ${GREEN}Target:  $max_version${NC}"

                if cargo update -p "$crate_name" --precise "$max_version" 2>/dev/null; then
                    echo -e "    ${GREEN}✓ Updated${NC}"
                    ((UPDATED++))
                else
                    echo -e "    ${RED}✗ Failed to update${NC}"
                    ((FAILED++))
                fi
                echo ""
            fi
        fi
    fi
done

# Summary
echo -e "${CYAN}════════════════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}Results:${NC}"
echo -e "  ${GREEN}Updated: $UPDATED${NC}"
echo -e "  ${YELLOW}Skipped: $SKIPPED${NC}"
echo -e "  ${RED}Failed:  $FAILED${NC}"
echo -e "${CYAN}════════════════════════════════════════════════════════════════════${NC}"
echo ""

# Step 4: Verify
echo -e "${YELLOW}Step 4: Verifying${NC}"
ISSUES=0

for entry in "${CRATES_TO_FIX[@]}"; do
    crate_name="${entry%%:*}"
    max_version="${entry##*:}"

    if grep -q "name = \"$crate_name\"" Cargo.lock 2>/dev/null; then
        found_version=$(grep -A1 "name = \"$crate_name\"" Cargo.lock | grep "version" | head -1 | sed 's/.*"\([^"]*\)".*/\1/')

        if [ -n "$found_version" ]; then
            higher_version=$(echo -e "$found_version\n$max_version" | sort -V | tail -1)
            if [ "$higher_version" = "$found_version" ] && [ "$found_version" != "$max_version" ]; then
                echo -e "  ${RED}⚠ $crate_name: $found_version (should be <= $max_version)${NC}"
                ((ISSUES++))
            fi
        fi
    fi
done

echo ""
if [ $ISSUES -eq 0 ]; then
    echo -e "${GREEN}════════════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}✓ All dependencies should now be compatible with Solana toolchain!${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════════════════════════${NC}"
else
    echo -e "${YELLOW}════════════════════════════════════════════════════════════════════${NC}"
    echo -e "${YELLOW}⚠ Some crates could not be downgraded automatically.${NC}"
    echo -e "${YELLOW}  You may need to add [patch.crates-io] to your Cargo.toml.${NC}"
    echo -e "${YELLOW}════════════════════════════════════════════════════════════════════${NC}"
fi

echo ""
echo -e "${CYAN}Next steps:${NC}"
echo "  1. Try building: cargo build-sbf"
echo "  2. Or with Anchor: anchor build"
echo ""
echo -e "${DIM}Report issues: https://github.com/volta-team/solana-edition-fixer/issues${NC}"
echo ""
